### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by FireMasterK** [cloudflare/cloudflared#259]
OS: Windows 10

```
C:\Users\kavin>cloudflared tunnel --url http://localhost:7000
INFO[2020-11-15T00:54:50+05:30] Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp]
INFO[2020-11-15T00:54:50+05:30] Version 2020.11.5
INFO[2020-11-15T00:54:50+05:30] GOOS: windows, GOVersion: go1.15.3, GoArch: amd64
INFO[2020-11-15T00:54:50+05:30] Environment variables map[proxy-dns-upstream:https://1.1.1.1/dns-query, https://1.0.0.1/dns-query url:http://localhost:7000]
INFO[2020-11-15T00:54:50+05:30] Starting metrics server on 127.0.0.1:1080/metrics
INFO[2020-11-15T00:54:50+05:30] cloudflared will not automatically update on Windows systems.
INFO[2020-11-15T00:54:50+05:30] Initial protocol h2mux
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0xd386ca]

goroutine 1 [running]:
github.com/cloudflare/cloudflared/tlsconfig.LoadOriginCA(0x0, 0x0, 0x0, 0x0, 0x1464d20, 0xc00050c200, 0x7)
        /cfsetup_build/tlsconfig/certreloader.go:84 +0xea
github.com/cloudflare/cloudflared/ingress.newHTTPTransport(0x163fca0, 0xc000249520, 0x6fc23ac00, 0x2540be400, 0x6fc23ac00, 0x0, 0x64, 0x14f46b0400, 0x0, 0x0, ...)
        /cfsetup_build/ingress/origin_service.go:278 +0x67
github.com/cloudflare/cloudflared/ingress.(*localService).start(0xc000249520, 0xc0002bd490, 0x1652240, 0xc00026da40, 0xc0003ec0c0, 0xc00063ca80, 0x6fc23ac00, 0x2540be400, 0x6fc23ac00, 0x0, ...)
        /cfsetup_build/ingress/origin_service.go:92 +0x7e
github.com/cloudflare/cloudflared/ingress.Ingress.StartOrigins(0xc00032c0c0, 0x1, 0x1, 0x6fc23ac00, 0x2540be400, 0x6fc23ac00, 0x0, 0x64, 0x14f46b0400, 0x0, ...)
        /cfsetup_build/ingress/ingress.go:117 +0x175
github.com/cloudflare/cloudflared/cmd/cloudflared/tunnel.StartServer(0xc0000c7a40, 0x16106e0, 0x9, 0xc0003ec0c0, 0xc0003ec120, 0x0, 0x1652240, 0xc00026da40, 0x0, 0x0, ...)
        /cfsetup_build/cmd/cloudflared/tunnel/cmd.go:375 +0xa48
github.com/cloudflare/cloudflared/cmd/cloudflared/tunnel.runClassicTunnel(...)
        /cfsetup_build/cmd/cloudflared/tunnel/cmd.go:199
github.com/cloudflare/cloudflared/cmd/cloudflared/tunnel.TunnelCommand(0xc0000c7a40, 0x1644e00, 0xc0005a0360)
        /cfsetup_build/cmd/cloudflared/tunnel/cmd.go:163 +0x192
github.com/cloudflare/cloudflared/cmd/cloudflared/cliutil.ErrorHandler.func1(0xc0000c7a40, 0x0, 0x0)
        /cfsetup_build/cmd/cloudflared/cliutil/errors.go:32 +0x8f
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000084900, 0xc0000c6440, 0x0, 0x0)
        /cfsetup_build/vendor/github.com/urfave/cli/v2/app.go:432 +0x9d4
github.com/urfave/cli/v2.(*Command).startApp(0xc000451e60, 0xc0000c6440, 0x149a149, 0xc0000320c8)
        /cfsetup_build/vendor/github.com/urfave/cli/v2/command.go:279 +0x6bb
github.com/urfave/cli/v2.(*Command).Run(0xc000451e60, 0xc0000c6440, 0x0, 0x0)
        /cfsetup_build/vendor/github.com/urfave/cli/v2/command.go:94 +0x9cd
github.com/urfave/cli/v2.(*App).RunContext(0xc000084780, 0x1644760, 0xc000032028, 0xc000038080, 0x4, 0x4, 0x0, 0x0)
        /cfsetup_build/vendor/github.com/urfave/cli/v2/app.go:306 +0x83f
github.com/urfave/cli/v2.(*App).Run(...)
        /cfsetup_build/vendor/github.com/urfave/cli/v2/app.go:215
main.runApp(0xc000084780, 0xc0003ec0c0, 0xc0003ec120)
        /cfsetup_build/cmd/cloudflared/windows_service.go:81 +0x4c5
main.main()
        /cfsetup_build/cmd/cloudflared/main.go:86 +0x575
```

**Comment by adamchalmers** [comment]
Hi, thanks for reporting this. I'm cutting a new release to fix the issue as we speak.

**Comment by adamchalmers** [comment]
Release 2020.11.6 includes [6159cb536f9](https://github.com/cloudflare/cloudflared/commit/6159cb536f9622125baebaeff32b84c028717e67) which should fix this. Please reopen this if 2020.11.6 doesn't fix your problem -- I think this only occurs on Windows so I haven't replicated it personally.
