### ISSUE TITLE
http panic: multiple registrations for /debug/request on mips build

### ISSUE THREAD

**Issue by platten** [cloudflare/cloudflared#31]
I have built `cloudflared` using go 1.10.2 for my Ubiquiti USG (linux/mips64) and I keep running into this error (it happens with every `cloudflared` subcommand). Any ideas how I can resolve this?

```
vbash-4.1# /usr/local/bin/cloudflared service install
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x1086d40, 0xa880f5, 0xf, 0xb748a0, 0xaf89c8)
        /usr/local/Cellar/go/1.10.2/libexec/src/net/http/server.go:2353 +0x2a8
net/http.(*ServeMux).HandleFunc(0x1086d40, 0xa880f5, 0xf, 0xaf89c8)
        /usr/local/Cellar/go/1.10.2/libexec/src/net/http/server.go:2368 +0x64
net/http.HandleFunc(0xa880f5, 0xf, 0xaf89c8)
        /usr/local/Cellar/go/1.10.2/libexec/src/net/http/server.go:2380 +0x5c
github.com/coredns/coredns/vendor/golang.org/x/net/trace.init.0()
        /Users/paul/go/src/github.com/coredns/coredns/vendor/golang.org/x/net/trace/trace.go:115 +0x5c
```

I tried building it on go darwin 1.10.2 (`GOOS=linux GOARCH=mips go build -v -x github.com/cloudflare/cloudflared/cmd/cloudflared` and `GOOS=linux GOARCH=mips64 go build -v -x github.com/cloudflare/cloudflared/cmd/cloudflared`) as well as within docker using:
```
docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp -e GOOS=linux -e GOARCH=mips golang bash -c "go get -v github.com/cloudflare/cloudflared/cmd/cloudflared; GOOS=linux GOARCH=mips go build -v -x github.com/cloudflare/cloudflared/cmd/cloudflared"

docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp -e GOOS=linux -e GOARCH=mips golang bash -c "go get -v github.com/cloudflare/cloudflared/cmd/cloudflared; GOOS=linux GOARCH=mips64 go build -v -x github.com/cloudflare/cloudflared/cmd/cloudflared"

docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp -e GOOS=linux -e GOARCH=mips golang:9.6.2 bash -c "go get -v github.com/cloudflare/cloudflared/cmd/cloudflared; GOOS=linux GOARCH=mips go build -v -x github.com/cloudflare/cloudflared/cmd/cloudflared"

docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp -e GOOS=linux -e GOARCH=mips golang:9.6.2 bash -c "go get -v github.com/cloudflare/cloudflared/cmd/cloudflared; GOOS=linux GOARCH=mips64 go build -v -x github.com/cloudflare/cloudflared/cmd/cloudflared"
```

Any help would be most appreciated!

**Comment by moderation** [comment]
@platten I was hitting this on Linux amd64 and aarch64 and MacOS. The issue is a conflict with the vendored coredns library.

The way I was able to fix was `rm -rf $GOPATH/src/github.com/coredns/coredns/vendor/golang.org/x/net/trace/` and then build again.

I found this fix via https://github.com/coreos/etcd/issues/9357#issuecomment-377560659
