### ISSUE TITLE
cloudflared panics (and recover) in loop, affecting traffic

### ISSUE THREAD

**Issue by Gilthoniel** [cloudflare/cloudflared#523]
We're seeing the same issue already mentioned in #450 but this issue is currently impacting the traffic on our components. That's why I'm reopening an issue, I hope it's ok.

```
Recover from http2 response writer panic, error goroutine 54471891 [running]:
runtime/debug.Stack(0xc00273d568, 0xf9e340, 0x12e0100)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/cloudflare/cloudflared/connection.(*http2RespWriter).Write.func1()
	/cfsetup_build/connection/http2.go:234 +0x46
panic(0xf9e340, 0x12e0100)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
golang.org/x/net/http2.(*responseWriter).write(0xc000278010, 0x4, 0xc00015c8b8, 0x4, 0x14, 0x0, 0x0, 0x10, 0xc0004040a0, 0xc0013260a0)
	/cfsetup_build/vendor/golang.org/x/net/http2/server.go:2692 +0x1f7
golang.org/x/net/http2.(*responseWriter).Write(0xc000278010, 0xc00015c8b8, 0x4, 0x14, 0x2, 0x2, 0xc00273d848)
	/cfsetup_build/vendor/golang.org/x/net/http2/server.go:2681 +0x56
github.com/cloudflare/cloudflared/connection.(*http2RespWriter).Write(0xc002cea700, 0xc00015c8b8, 0x4, 0x14, 0x0, 0x0, 0x0)
	/cfsetup_build/connection/http2.go:237 +0x8c
github.com/cloudflare/cloudflared/connection.(*HTTPResponseReadWriteAcker).Write(0xc003a94540, 0xc00015c8b8, 0x4, 0x14, 0x0, 0x0, 0xc00046a888)
	/cfsetup_build/connection/connection.go:138 +0x52
github.com/gobwas/ws/wsutil.(*Writer).flushFragment(0xc0020cec00, 0x1, 0x0, 0x0)
	/cfsetup_build/vendor/github.com/gobwas/ws/wsutil/writer.go:406 +0x253
github.com/gobwas/ws/wsutil.(*Writer).Flush(0xc0020cec00, 0xc00015c8b8, 0x2)
	/cfsetup_build/vendor/github.com/gobwas/ws/wsutil/writer.go:367 +0x65
github.com/gobwas/ws/wsutil.(*ControlWriter).Flush(...)
	/cfsetup_build/vendor/github.com/gobwas/ws/wsutil/writer.go:84
github.com/gobwas/ws/wsutil.ControlHandler.HandleClose(0x12f53e0, 0xc00250dc80, 0x7fc614733f30, 0xc003a94540, 0x101, 0xceb00c2101080001, 0x12, 0x0, 0x0)
	/cfsetup_build/vendor/github.com/gobwas/ws/wsutil/handler.go:202 +0x2c5
github.com/gobwas/ws/wsutil.ControlHandler.Handle(0x12f53e0, 0xc00250dc80, 0x7fc614733f30, 0xc003a94540, 0x101, 0xceb00c2101080001, 0x12, 0x0, 0x0)
	/cfsetup_build/vendor/github.com/gobwas/ws/wsutil/handler.go:64 +0x13a
github.com/gobwas/ws/wsutil.ControlFrameHandler.func1(0xceb00c2101080001, 0x12, 0x12f53e0, 0xc00250dc80, 0x0, 0x0)
	/cfsetup_build/vendor/github.com/gobwas/ws/wsutil/helper.go:244 +0x9f
github.com/gobwas/ws/wsutil.readData(0x7fc614733e60, 0xc003a94540, 0x500201, 0xc001124080, 0xc0016c0000, 0x2a, 0x8000, 0x2a, 0x0)
	/cfsetup_build/vendor/github.com/gobwas/ws/wsutil/helper.go:263 +0x2cc
github.com/gobwas/ws/wsutil.ReadClientBinary(...)
	/cfsetup_build/vendor/github.com/gobwas/ws/wsutil/helper.go:118
github.com/cloudflare/cloudflared/websocket.(*Conn).Read(0xc002d5f5a0, 0xc0016c0000, 0x8000, 0x8000, 0x2a, 0x0, 0x0)
	/cfsetup_build/websocket/connection.go:117 +0x45
io.copyBuffer(0x12f8640, 0xc0025089a0, 0x7fc614733eb0, 0xc002d5f5a0, 0xc0016c0000, 0x8000, 0x8000, 0xc0002da2c0, 0x0, 0x160)
	/usr/local/go/src/io/io.go:423 +0x12c
io.Copy(...)
	/usr/local/go/src/io/io.go:382
net.genericReadFrom(0x12f6cc0, 0xc001124080, 0x7fc614733eb0, 0xc002d5f5a0, 0x0, 0x0, 0x100b300)
	/usr/local/go/src/net/net.go:655 +0x9a
net.(*TCPConn).readFrom(0xc001124080, 0x7fc614733eb0, 0xc002d5f5a0, 0x0, 0xc00139b638, 0x40baca)
	/usr/local/go/src/net/tcpsock_posix.go:54 +0xe9
net.(*TCPConn).ReadFrom(0xc001124080, 0x7fc614733eb0, 0xc002d5f5a0, 0x7fc614733ef0, 0xc001124080, 0x1)
	/usr/local/go/src/net/tcpsock.go:103 +0x4d
io.copyBuffer(0x12f6cc0, 0xc001124080, 0x7fc614733eb0, 0xc002d5f5a0, 0x0, 0x0, 0x0, 0x10570a0, 0xc00139b700, 0x7fc614733eb0)
	/usr/local/go/src/io/io.go:409 +0x357
io.Copy(...)
	/usr/local/go/src/io/io.go:382
github.com/cloudflare/cloudflared/websocket.copyData(0x12f6cc0, 0xc001124080, 0x7fc614733eb0, 0xc002d5f5a0, 0x116e2ba, 0xe, 0x130b390, 0xc001648000, 0x7240b1)
	/cfsetup_build/websocket/websocket.go:98 +0x5a
github.com/cloudflare/cloudflared/websocket.Stream.func2(0x7fc614733e88, 0xc001124080, 0x12fe7f0, 0xc002d5f5a0, 0xc000115740, 0xc0020a72c0)
	/cfsetup_build/websocket/websocket.go:44 +0xca
created by github.com/cloudflare/cloudflared/websocket.Stream
	/cfsetup_build/websocket/websocket.go:43 +0xe7
```

**Comment by Gilthoniel** [comment]
Nevermind, it does not impact the traffic
