### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [cloudflare/cloudflared#587]
**Describe the bug**
I found a weird bug in my logs.

**To Reproduce**
i currently do not know how.

**Environment and versions**
 - OS: Debian 11 on i9 12900k
 - Architecture: [AMD64]
 - Version: [latest as of post]

**Logs and errors**

2022-02-28T14:23:56Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: EOF" cfRay=*******-EWR ingressRule=3 originService=http://127.0.0.1:6009
2022-02-28T14:23:57Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: EOF" cfRay=*******-EWR ingressRule=3 originService=http://127.0.0.1:6009
2022-02-28T16:08:06Z INF Lost connection with the edge connIndex=2
2022-02-28T16:08:06Z INF Unregistered tunnel connection connIndex=2
2022-02-28T16:08:06Z WRN Serve tunnel error error="connection with edge closed" connIndex=2
2022-02-28T16:08:06Z INF Retrying connection in up to 1s seconds connIndex=2
2022-02-28T16:08:07Z INF Connection ******* registered connIndex=2 location=AMS
Recover from http2 response writer panic, error goroutine 5915415 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/cloudflare/cloudflared/connection.(*http2RespWriter).Write.func1()
        /cfsetup_build/connection/http2.go:236 +0x2f
panic({0xe7ed40, 0x11acd70})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
golang.org/x/net/http2.(*responseWriter).Flush(0x10101c000b69638)
        /cfsetup_build/vendor/golang.org/x/net/http2/server.go:2594 +0x67
github.com/cloudflare/cloudflared/connection.(*http2RespWriter).Write(0xc000b0da00, {0xc000bbe000, 0xe7efc0, 0xc000456201})
        /cfsetup_build/connection/http2.go:241 +0x91
github.com/cloudflare/cloudflared/origin.(*bidirectionalStream).Write(0xd, {0xc000bbe000, 0xc000456260, 0xc000b696f0})
        /cfsetup_build/origin/proxy.go:268 +0x27
io.copyBuffer({0x7f29ecdc89d0, 0xc000456260}, {0x7f29ecdc89f0, 0xc000d86ee8}, {0x0, 0x0, 0x0})
        /usr/local/go/src/io/io.go:425 +0x204
io.Copy(...)
        /usr/local/go/src/io/io.go:382
github.com/cloudflare/cloudflared/websocket.copyData({0x7f29ecdc89d0, 0xc000456260}, {0x7f29ecdc89f0, 0xc000d86ee8}, {0x19aba58, 0x0})
        /cfsetup_build/websocket/websocket.go:98 +0x35
github.com/cloudflare/cloudflared/websocket.Stream.func1()
        /cfsetup_build/websocket/websocket.go:36 +0xa5
created by github.com/cloudflare/cloudflared/websocket.Stream
        /cfsetup_build/websocket/websocket.go:35 +0xf6

2022-02-28T23:07:04Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: EOF" cfRay=*******-ORD ingressRule=6 originService=http://127.0.0.1:6006

**Additional context**
RayID or other details may be requested my emailing me: admin@trycs.net

**Comment by nmldiegues** [comment]
This one

```
2022-02-28T14:23:57Z ERR error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: EOF" cfRay=-EWR ingressRule=3 originService=http://127.0.0.1:6009/
```

means that your origin (i.e. server) http://127.0.0.1:6009/ dropped the connection unexpectedly, hence the "EOF" error


The other one:
```
Recover from http2 response writer panic,
```

is harmless in practice; we have even considered not printing that, as it confuses users more than anything
