### ISSUE TITLE
🐛 github.com/cloudflare/cloudflared/proxy test failure

### ISSUE THREAD

**Issue by frebib** [cloudflare/cloudflared#751]
**Describe the bug**
```
panic: test timed out after 10m0s

goroutine 41 [running]:
testing.(*M).startAlarm.func1()
	/usr/lib/go/src/testing/testing.go:2036 +0x8e
created by time.goFunc
	/usr/lib/go/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000103ba0, {0xe733c9?, 0x5204a5?}, 0xf07d68)
	/usr/lib/go/src/testing/testing.go:1494 +0x37a
testing.runTests.func1(0xc000103ba0?)
	/usr/lib/go/src/testing/testing.go:1846 +0x6e
testing.tRunner(0xc000103ba0, 0xc00035fcd8)
	/usr/lib/go/src/testing/testing.go:1446 +0x10b
testing.runTests(0xc000539180?, {0x161d0c0, 0x5, 0x5}, {0x7f5d90a1b5b8?, 0x40?, 0x1683760?})
	/usr/lib/go/src/testing/testing.go:1844 +0x456
testing.(*M).Run(0xc000539180)
	/usr/lib/go/src/testing/testing.go:1726 +0x5d9
main.main()
	_testmain.go:55 +0x1aa

goroutine 36 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000696340, {0xe71682?, 0x1?}, 0xf07d90)
	/usr/lib/go/src/testing/testing.go:1494 +0x37a
github.com/cloudflare/cloudflared/proxy.TestProxySingleOrigin(0xc000696340)
	/home/frebib/.cache/yay/cloudflared/src/cloudflared/proxy/proxy_test.go:159 +0x5ee
testing.tRunner(0xc000696340, 0xf07d68)
	/usr/lib/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1493 +0x35f

goroutine 77 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7f5d68946ef8, 0x72)
	/usr/lib/go/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc00004e300?, 0x6?, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00004e300)
	/usr/lib/go/src/internal/poll/fd_unix.go:614 +0x234
net.(*netFD).accept(0xc00004e300)
	/usr/lib/go/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc00064e450)
	/usr/lib/go/src/net/tcpsock_posix.go:142 +0x28
net.(*TCPListener).Accept(0xc00064e450)
	/usr/lib/go/src/net/tcpsock.go:288 +0x3d
crypto/tls.(*listener).Accept(0xc00064e468)
	/usr/lib/go/src/crypto/tls/tls.go:66 +0x2d
net/http.(*Server).Serve(0xc00016c1e0, {0xff9e90, 0xc00064e468})
	/usr/lib/go/src/net/http/server.go:3070 +0x385
github.com/cloudflare/cloudflared/hello.StartHelloWorldServer(0xff50e0?, {0xff9e90, 0xc00064e468}, 0xc000896000)
	/home/frebib/.cache/yay/cloudflared/src/cloudflared/hello/hello.go:126 +0x3c8
created by github.com/cloudflare/cloudflared/ingress.(*helloWorld).start
	/home/frebib/.cache/yay/cloudflared/src/cloudflared/ingress/origin_service.go:227 +0x12d

goroutine 39 [chan receive, 9 minutes]:
github.com/cloudflare/cloudflared/proxy.testProxySSEAllData.func1(0x82019f?)
	/home/frebib/.cache/yay/cloudflared/src/cloudflared/proxy/proxy_test.go:287 +0x2d9
testing.tRunner(0xc000802680, 0xf07d90)
	/usr/lib/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1493 +0x35f

goroutine 99 [chan receive, 9 minutes]:
github.com/cloudflare/cloudflared/hello.StartHelloWorldServer.func1()
	/home/frebib/.cache/yay/cloudflared/src/cloudflared/hello/hello.go:122 +0x28
created by github.com/cloudflare/cloudflared/hello.StartHelloWorldServer
	/home/frebib/.cache/yay/cloudflared/src/cloudflared/hello/hello.go:121 +0x3ab
FAIL	github.com/cloudflare/cloudflared/proxy	600.014s
```

**To Reproduce**
Install the `cloudflared` package from the Arch Linux AUR: https://aur.archlinux.org/packages/cloudflared

Sami reported this too https://aur.archlinux.org/packages/cloudflared#comment-880091

**Environment and versions**
 - OS: Arch Linux
 - Architecture: x86_64
 - Version: yes

**Comment by nmldiegues** [comment]
> Version: yes

Is this against latest master, namely one that contains https://github.com/cloudflare/cloudflared/commit/4ac68711cd9c3d54b6b474ef03a4225d62e03d3c ?
There were a bunch of tests failing, which were not caught by Linux on our internal CI, but they've been addressed, and now Github CI is passing on all 3 OS as well.

**Comment by frebib** [comment]
Oh, by `Version` I assumed it meant `OS Version` (arch is rolling release) - my bad. AUR has 2022.8.4 pinned, but I can confirm 4ac68711cd9c3d54b6b474ef03a4225d62e03d3c builds just fine.
Thanks

**Comment by nmldiegues** [comment]
Great to hear that.

I guess we'll make a 2022.9.0 soon too, so that'll close the matter.
