### ISSUE TITLE
Crash on Linux when using bastion mode without a config

### ISSUE THREAD

**Issue by ArielPrevu3D** [cloudflare/cloudflared#902]
**Describe the bug**
When a cloudflared client connects, the cloudflared process crashes with the following error logged.

```
panic: runtime error: index out of range [-1]	CFTunnelContainer
goroutine 215 [running]:	CFTunnelContainer
github.com/cloudflare/cloudflared/ingress.Ingress.FindMatchingRule({{0x0, 0x0, 0x0}, {{0x0}, {0x0}, {0x0}, 0x0, {0x0}, 0x0, {0x0, ...}, ...}}, ...)	CFTunnelContainer
/cfsetup_build/ingress/ingress.go:51 +0xef	CFTunnelContainer
github.com/cloudflare/cloudflared/proxy.(*Proxy).ProxyHTTP(0xc000546b40, {0x13d0158?, 0xc00061d360}, 0xc0009db9c8, 0x60?)	CFTunnelContainer
/cfsetup_build/proxy/proxy.go:96 +0x465	CFTunnelContainer
github.com/cloudflare/cloudflared/connection.(*QUICConnection).dispatchRequest(0xc0001bcd90, {0x13d2ad8, 0xc000826100}, 0xc00061d260, {0x10?, 0xc000067800?}, 0xc000ae3d40)	CFTunnelContainer
/cfsetup_build/connection/quic.go:268 +0x263	CFTunnelContainer
github.com/cloudflare/cloudflared/connection.(*QUICConnection).handleDataStream(0xc0001bcd90, {0x13d2ad8, 0xc000826100}, 0xc000067800?)	CFTunnelContainer
/cfsetup_build/connection/quic.go:235 +0x79	CFTunnelContainer
github.com/cloudflare/cloudflared/connection.(*QUICConnection).handleStream(0xc000146480?, {0x13d2ad8, 0xc000826100}, {0x13d0188?, 0xc0009db938})	CFTunnelContainer
/cfsetup_build/connection/quic.go:217 +0x175	CFTunnelContainer
github.com/cloudflare/cloudflared/connection.(*QUICConnection).runStream(0xc0001bcd90, {0x7f9efffee848, 0xc0007d0000})	CFTunnelContainer
/cfsetup_build/connection/quic.go:197 +0x128	CFTunnelContainer
created by github.com/cloudflare/cloudflared/connection.(*QUICConnection).acceptStream	CFTunnelContainer
/cfsetup_build/connection/quic.go:183 +0x88	CFTunnelContainer
```

**To Reproduce**
1. `cloudflared tunnel --loglevel debug --cred-file /tunnel_creds.json run  --bastion <tunnel_id>`
2. Use cloudflared to connect `cloudflared access tcp -T  https://tunnel.myurl.com -L 127.0.0.1:1234 --destination https://mydestination.com)`
3. See error and crash

**Expected behavior**
I expect cloudflared not to crash, and route my bastion connection request.

**Environment and versions**
 - OS: Ubuntu 20.0.4 LTS (Docker)
 - Architecture: AMD64
 - Version: 2023.2.2

**Logs and errors**
Look up

**Additional context**
Nope

**Comment by Erisa** [comment]
I also get this error just from `docker run cloudflare/cloudflared --hello-world`

```
erisa@ubuntu:~$ docker run cloudflare/cloudflared --hello-world
2023-03-02T19:10:16Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2023-03-02T19:10:16Z INF Requesting new quick Tunnel on trycloudflare.com...
2023-03-02T19:10:18Z INF +--------------------------------------------------------------------------------------------+
2023-03-02T19:10:18Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2023-03-02T19:10:18Z INF |  https://litigation-authentic-computation-sa.trycloudflare.com                             |
2023-03-02T19:10:18Z INF +--------------------------------------------------------------------------------------------+
2023-03-02T19:10:18Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2023-03-02T19:10:18Z INF Version 2023.3.0
2023-03-02T19:10:18Z INF GOOS: linux, GOVersion: go1.19.6, GoArch: amd64
2023-03-02T19:10:18Z INF Settings: map[hello-world:true no-autoupdate:true protocol:quic]
2023-03-02T19:10:18Z INF Generated Connector ID: eee17f49-355a-461f-bc93-5571689e49d5
2023-03-02T19:10:18Z INF Initial protocol quic
2023-03-02T19:10:18Z INF ICMP proxy will use 172.17.0.3 as source for IPv4
2023-03-02T19:10:18Z INF ICMP proxy will use :: as source for IPv6
2023-03-02T19:10:18Z INF Starting metrics server on 127.0.0.1:44599/metrics
2023/03/02 19:10:18 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2023-03-02T19:10:19Z INF Connection ab3a6dd1-5bc6-4be0-8b82-6de4b0520ba6 registered with protocol: quic connIndex=0 ip=198.41.192.167 location=FRA
2023-03-02T19:10:19Z INF Connection 5da24823-a499-4be2-8448-3d7c9c1033fd registered with protocol: quic connIndex=1 ip=198.41.200.13 location=VIE
2023-03-02T19:10:21Z INF Connection 46fd2b24-6333-49a7-9d63-2273e27a4aa3 registered with protocol: quic connIndex=2 ip=198.41.192.227 location=FRA
2023-03-02T19:10:22Z INF Connection 922b9af9-9c49-45e5-966f-5bb14f9f7a03 registered with protocol: quic connIndex=3 ip=198.41.200.53 location=VIE
panic: runtime error: index out of range [-1]

goroutine 202 [running]:
github.com/cloudflare/cloudflared/ingress.Ingress.FindMatchingRule({{0x0, 0x0, 0x0}, {{0x0}, {0x0}, {0x0}, 0x0, {0x0}, 0x0, {0x0, ...}, ...}}, ...)
        /go/src/github.com/cloudflare/cloudflared/ingress/ingress.go:51 +0xef
github.com/cloudflare/cloudflared/proxy.(*Proxy).ProxyHTTP(0xc000094c60, {0x13d2078?, 0xc0000802c0}, 0xc0007930c8, 0x10?)
        /go/src/github.com/cloudflare/cloudflared/proxy/proxy.go:96 +0x465
github.com/cloudflare/cloudflared/connection.(*QUICConnection).dispatchRequest(0xc0002b7c70, {0x13d49f8, 0xc000041b80}, 0xc000080110, {0x10?, 0xc00006e400?}, 0xc000184540)
        /go/src/github.com/cloudflare/cloudflared/connection/quic.go:269 +0x263
github.com/cloudflare/cloudflared/connection.(*QUICConnection).handleDataStream(0xc0002b7c70, {0x13d49f8, 0xc000041b80}, 0xc00006e400?)
        /go/src/github.com/cloudflare/cloudflared/connection/quic.go:236 +0x79
github.com/cloudflare/cloudflared/connection.(*QUICConnection).handleStream(0xc00052cb01?, {0x13d49f8, 0xc000041b80}, {0x13d20a8?, 0xc000792fc0})
        /go/src/github.com/cloudflare/cloudflared/connection/quic.go:218 +0x175
github.com/cloudflare/cloudflared/connection.(*QUICConnection).runStream(0xc0002b7c70, {0x7f9f9c8923c8, 0xc000154000})
        /go/src/github.com/cloudflare/cloudflared/connection/quic.go:198 +0x128
created by github.com/cloudflare/cloudflared/connection.(*QUICConnection).acceptStream
        /go/src/github.com/cloudflare/cloudflared/connection/quic.go:184 +0x88
```

Panic happens upon sending the first request to the URL

**Comment by DevinCarr** [comment]
I know what caused this, I'll hopefully have a correction out for this soon. This should only impact users that are attempting to run tunnels with argument flags and no config.yaml (i.e using `--bastion` or `--hello-world`). Bug introduced here: https://github.com/cloudflare/cloudflared/commit/ae46af9236aca8df7dc8e9ae62b0fc3db4be1662#diff-47537d8b0df58c3254301cc72841800591e7ed9f14719067d43243ad66493e09R257-R269

**Comment by Erisa** [comment]
Hey Devin, thanks for the update and reassurance that it only affects these cases! 🙂

**Comment by ArielPrevu3D** [comment]
> This should be fixed with this change: [93f8f6b](https://github.com/cloudflare/cloudflared/commit/93f8f6b55cf3270a65f58094ffd8a0bcc080bac2)
> 
> We will likely do a release soon to include this change.

Amazing, thank you!

**Comment by batonac** [comment]
Actually, in my case, I get the same error but due to a slightly different issue. Before 2023.3.0, cloudflared was working without a dedicated `ingress` key in config.yml. I could simply specify: `unix-socket: /run/nginx.sock` as a root-level param. Now, I apparently need an `ingress` key with a sub-key `  - service: unix:/run/nginx.sock`...

**Comment by Erisa** [comment]
This is now working for me again as of 2023.3.1

**Comment by sudarshan-reddy** [comment]
> Actually, in my case, I get the same error but due to a slightly different issue. Before 2023.3.0, cloudflared was working without a dedicated ingress key in config.yml. I could simply specify: unix-socket: /run/nginx.sock as a root-level param. Now, I apparently need an ingress key with a sub-key   - service: unix:/run/nginx.sock...

What is the exact command you used to run for cloudflared to start?

**Comment by batonac** [comment]
Sorry for the delay on this. I was using systemd to start. The issue is completely resolved with the update, so this bug was my bug as well, even if we triggered it for different reasons.
