### ISSUE TITLE
🐛 cloudflared 2023.3.0 broken on MacOS ARM64 

### ISSUE THREAD

**Issue by code-ape** [cloudflare/cloudflared#907]
**Describe the bug**
> A clear and concise description of what the bug is.

I updated my `cloudflared` from 2023.2.1 to 2023.3.0 on MacOS via `brew` today at ~6:30pm EST. After the update, when I start a tunnel, it crashes as soon as the first request comes in. The webpage for the request shows an error page.

**To Reproduce**
> Steps to reproduce the behavior:

1. Have a MacOS machine with ARM64 M1 processor.
2. Install cloudflared via `brew install`.
3. Run: `cloudflared tunnel run --token "MY_TOKEN" --hello-world`
4. Make a request to the tunnel via the public URL for it using Safari desktop browser.

**Expected behavior**
> A clear and concise description of what you expected to happen.

The tunnel handles the request and does not crash.

**Environment and versions**
 - OS: MacOS 12.6
 - Architecture: ARM64
 - Version: 2023.3.0
 - SHA256 sum: `c121264346237ef4551109872035d9809cf8e22f188e2b2ca55e684f619f3a9b  /opt/homebrew/bin/cloudflared`

**Logs and errors**
> If applicable, add logs or errors to help explain your problem.

See below log, details intentional obscured.

```
% cloudflared tunnel run --token "MY_TOKEN" --hello-world
2023-03-06T23:55:46Z INF Starting tunnel tunnelID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
2023-03-06T23:55:46Z INF Version 2023.3.0
2023-03-06T23:55:46Z INF GOOS: darwin, GOVersion: go1.19.3, GoArch: amd64
2023-03-06T23:55:46Z INF Settings: map[hello-world:true token:*****]
2023-03-06T23:55:46Z INF cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/as-a-service/
2023-03-06T23:55:46Z INF Generated Connector ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
2023-03-06T23:55:46Z INF Initial protocol quic
2023-03-06T23:55:46Z INF ICMP proxy will use yyy.yyy.yyy.yyy as source for IPv4
2023-03-06T23:55:46Z INF ICMP proxy will use fe80::zz:zzzz:zzzz:zzzz in zone en0 as source for IPv6
2023-03-06T23:55:46Z INF Created ICMP proxy listening on yyy.yyy.yyy.yyy
2023-03-06T23:55:46Z INF Created ICMP proxy listening on [fe80::zz:zzzz:zzzz:zzzz]:0
2023-03-06T23:55:46Z INF Starting metrics server on 127.0.0.1:57649/metrics
2023-03-06T23:55:46Z INF Connection xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx registered with protocol: quic connIndex=0 ip=198.41.192.77 location=IAD
2023-03-06T23:55:47Z INF Connection xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx registered with protocol: quic connIndex=1 ip=198.41.200.113 location=ORD
2023-03-06T23:55:48Z INF Connection xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx registered with protocol: quic connIndex=2 ip=198.41.200.53 location=ORD
2023-03-06T23:55:49Z INF Connection xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx registered with protocol: quic connIndex=3 ip=198.41.192.67 location=IAD
panic: runtime error: index out of range [-1]

goroutine 232 [running]:
github.com/cloudflare/cloudflared/ingress.Ingress.FindMatchingRule({{0x0, 0x0, 0x0}, {{0x0}, {0x0}, {0x0}, 0x0, {0x0}, 0x0, {0x0, ...}, ...}}, ...)
        /opt/buildAgent/work/src/github.com/cloudflare/cloudflared/ingress/ingress.go:51 +0xef
github.com/cloudflare/cloudflared/proxy.(*Proxy).ProxyHTTP(0xc0006f50e0, {0x101053930?, 0xc0006fbfa0}, 0xc0008a03c0, 0xb0?)
        /opt/buildAgent/work/src/github.com/cloudflare/cloudflared/proxy/proxy.go:96 +0x465
github.com/cloudflare/cloudflared/connection.(*QUICConnection).dispatchRequest(0xc0002c1810, {0x1010562b8, 0xc000620940}, 0xc0006fbeb0, {0x10?, 0xc00027e000?}, 0xc0008cc150)
        /opt/buildAgent/work/src/github.com/cloudflare/cloudflared/connection/quic.go:269 +0x263
github.com/cloudflare/cloudflared/connection.(*QUICConnection).handleDataStream(0xc0002c1810, {0x1010562b8, 0xc000620940}, 0xc00027e000?)
        /opt/buildAgent/work/src/github.com/cloudflare/cloudflared/connection/quic.go:236 +0x79
github.com/cloudflare/cloudflared/connection.(*QUICConnection).handleStream(0x0?, {0x1010562b8, 0xc000620940}, {0x101053960?, 0xc0008a0330})
        /opt/buildAgent/work/src/github.com/cloudflare/cloudflared/connection/quic.go:218 +0x175
github.com/cloudflare/cloudflared/connection.(*QUICConnection).runStream(0xc0002c1810, {0x132d1b478, 0xc000926000})
        /opt/buildAgent/work/src/github.com/cloudflare/cloudflared/connection/quic.go:198 +0x128
created by github.com/cloudflare/cloudflared/connection.(*QUICConnection).acceptStream
        /opt/buildAgent/work/src/github.com/cloudflare/cloudflared/connection/quic.go:184 +0x88
```

**Additional context**
> Add any other context about the problem here.

1. I had no issues with 2023.2.1 and had it working with the exact same token. Only after running `brew update` to get version 2023.3.0 did I hit this error which consistently occurs.
2. Binary attached for convenience: [cloudflared.zip](https://github.com/cloudflare/cloudflared/files/10904038/cloudflared.zip)

**Comment by prsyahmi** [comment]
This occurred in windows too, version 2023.3.0, [2023.2.2](https://github.com/cloudflare/cloudflared/releases/tag/2023.2.2)
[2022.12.1](https://github.com/cloudflare/cloudflared/releases/tag/2022.12.1) works fine.
The crash happens right after the first user connect to the site
![image](https://user-images.githubusercontent.com/1040494/223425705-3dbd3dd1-13ab-45d7-bf33-f4c47adc5890.png)

**Comment by sudarshan-reddy** [comment]
Same as https://github.com/cloudflare/cloudflared/issues/902. @DevinCarr is on it!

**Comment by jshier** [comment]
It looks like 2023.3.1 is out with the fix but isn't available through `brew`. Can that release be triggered?

**Comment by jshier** [comment]
Thanks, looks like it's available now.

**Comment by sudarshan-reddy** [comment]
Thanks for noticing that @jshier . This should now be fixed.
